# yamllint disable-line rule:document-start
name: CI

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  php:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
      - name: Checkout the project
        uses: actions/checkout@v2

      - name: Setup the PHP ${{ matrix.php }} environment on ${{ runner.os }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Restore the Composer cache directory
        id: composercache
        run: echo "dir=$(composer config cache-files-dir)" >> "${GITHUB_OUTPUT}"

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composercache.outputs.dir }}
          # yamllint disable-line rule:line-length
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        # yamllint disable-line rule:line-length
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-suggest

      - name: Execute the PHP lint script
        run: composer run-script style:check
